server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://1.12.77.253:3306/test?useSSL=false
    username: qqq
    password: 123456qqq.
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo