server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://1.12.77.253:3306/test?useSSL=false
    username: qqq
    password: 123456qqq.
    driver-class-name: com.mysql.cj.jdbc.Driver
    rabbitmq:
      host: 192.168.88.130 # 主机名
      port: 5672 # 端口
      virtual-host: / # 虚拟主机
      username: itcast # 用户名
      password: 123456 # 密码
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo

